export const GETINDEXLIST_SUCCESS = 'GETINDEXLIST_SUCCESS'; // 请求首页列表成功
export const GETMUSICLIST_SUCCESS = 'GETMUSICLIST_SUCCESS'; // 请求音乐列表成功
export const GETMUSICLISTMORE_SUCCESS = 'GETMUSICLISTMORE_SUCCESS'; // 分页请求音乐列表成功
